# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\emojieditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmojiEditor(object):
    def setupUi(self, EmojiEditor):
        EmojiEditor.setObjectName("EmojiEditor")
        EmojiEditor.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(EmojiEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(EmojiEditor)
        QtCore.QMetaObject.connectSlotsByName(EmojiEditor)

    def retranslateUi(self, EmojiEditor):
        _translate = QtCore.QCoreApplication.translate
        EmojiEditor.setWindowTitle(_translate("EmojiEditor", "Dialog"))
